### ISSUE TITLE
makeActor does not work

### ISSUE THREAD

**Issue by esokullu** [pho-clients/js#3]
http -f POST 83.149.67.212:1337/actor param1=sokullu1
works
but
```javascript
var phonetworks = require('pho-js-client');
var api = new phonetworks.DefaultApi();
var callback = function(error, data, response) { console.log(data); };
api.makeActor({param1: "sokullu1"}, callback);
```
does **not**

> PS: param1 is the password parameter. Feel free to change its value to anything you like.

**Comment by mikoitoxin** [comment]
I have made a PR.
It should work now.
`var postBody = JSON.stringify(opts);`
